### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by okhabr**
- Implement the following pages:
  - landing-page
  - filter
  - result
  - pet
  - comparison
- Implement global state using redux, redux-saga, typesafe-actions

### CODE REVIEW

**Comment by okhabr** [comment]
This pull request duplicates request #72

**Review by Pashkaua — APPROVED** [review]
Congratulations on your first release!

**Review by enheit — APPROVED** [review]

**Review by ivan-bonk — APPROVED** [review]
Our work looks nice:)

**Review by Danik1702 — APPROVED** [review]
Congrats!

**Pull request merged**
